=== Zhibek18/parser_xml/src/main/resources/papers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/papers"
        xmlns:tns="http://www.example.com/papers"
        elementFormDefault="qualified">
    <element name="papers">
        <complexType>
            <sequence>
                <element    name="paper"
                            type="tns:Paper"
                            minOccurs="1"
                            maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Paper">
        <sequence>
            <element name="chars"
                        type="tns:Chars"
                        minOccurs="1"
                        maxOccurs="1"/>
        </sequence>
        <attribute name="title" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="([\w]+){2,20}"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="newspaper"/>
                    <enumeration value="magazine"/>
                    <enumeration value="booklet"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="monthly" type="boolean" use="optional" default="false"/>
    </complexType>
    <complexType name="Chars">
        <sequence>
            <element name="color" type="boolean"/>
            <element name="volume" type="positiveInteger"/>
            <element name="glossy" type="boolean" default="false"/>
            <element name="subscription-index" type="boolean" default="false"/>
        </sequence>
    </complexType>
</schema>

=== Zhibek18/parser_xml/src/main/resources/papers.xml
<?xml version="1.0" encoding="UTF-8"?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/papers"
          xsi:schemaLocation="http://www.example.com/papers papers.xsd">
    <paper title="Times" type="newspaper" monthly="true">
        <chars>
            <color>false</color>
            <volume>50</volume>
            <glossy></glossy>
            <subscription-index>true</subscription-index>    <!--subscription index-->
        </chars>
    </paper>
    <paper title="Cosmopolitan" type="magazine" monthly="true">
        <chars>
            <color>true</color>
            <volume>60</volume>
            <glossy>true</glossy>
            <subscription-index>true</subscription-index>    <!--subscription index-->
        </chars>
    </paper>
    <paper title="Space" type="booklet" monthly="false">
        <chars>
            <color>true</color>
            <volume>7</volume>
            <glossy>true</glossy>
            <subscription-index></subscription-index>
        </chars>
    </paper>
</papers>
